#:schema node_modules/wrangler/config-schema.json
name = "cold3"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[placement]
mode = "smart"

[observability]
enabled = true

[[kv_namespaces]]
binding = "OG_IMAGE_CACHE"
id = "ee95a879988944c2a7eb9521e62eb102"
